# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styleme', '0002_auto_20161121_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='clothing_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('name', models.CharField(default='', max_length=254)),
                ('owner', models.TextField()),
            ],
        ),
    ]
