# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styleme', '0004_auto_20161121_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='name',
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='tag',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
