# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styleme', '0005_auto_20161121_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='tag',
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='name',
            field=models.CharField(default='', max_length=254),
        ),
    ]
