# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styleme', '0006_auto_20161121_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='images/new-product.jpg', upload_to='images')),
            ],
        ),
    ]
