# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styleme', '0007_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
