# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('styleme', '0008_outfit_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
